### PR TITLE
doc: add Bryce Baril as a WG member

### PR DESCRIPTION
**Pull request by brycebaril**
See discussion here: https://github.com/nodejs/security-wg/issues/37

### CODE REVIEW

**Comment by brycebaril** [comment]
@sam-github done!

**Comment by sam-github** [comment]
@brycebaril can you land this, to show that the permissions all worked out and you have the auth to do so?

**Comment by brycebaril** [comment]
@sam-github not sure it's set up right quite yet:
```
ERROR: Permission to nodejs/security-wg.git denied to brycebaril.
```

**Comment by sam-github** [comment]
@brycebaril I added you, working now? I didn't think I had the power, sorry. You do, too, now, if my adding you worked.

**Pull request closed without merging**
