### PR TITLE
Relationship to private security activities

### PR DESCRIPTION
**Pull request by rvagg**
Proposed relationship and wording for that relationship. Comments?

/cc @nodejs/security

### CODE REVIEW

**Comment by indutny** [comment]
👍

**Comment by jasnell** [comment]
LGTM

**Comment by Trott** [comment]
Is there concern that people won't read that and assume that this repo is where they should report security issues? Might there be a better name for the repo/wg?

**Comment by Trott** [comment]
I should clarify that my questions above are not objections. This can totally land if it's all LGTMs and stuff. If anyone does want to consider a different name, perhaps something like "security policy wg" might be slightly better than just "security wg" even if it doesn't cover everything the wg will do.

**Comment by jbergstroem** [comment]
I think Rich has a good point. If the first line is "**dont report security issues here**" the naming could probably be improved. Never the less, wording is LGTM.

**Comment by sam-github** [comment]
Landed in 291f263c

**Comment by sam-github** [comment]
This is landable, but I don't have access rights to do so. I annotated with the landing meta-data: https://github.com/sam-github/security-wg/commit/91f263c3a3d8a5a86d0e66a61fe9bba9b552b131 @rvagg can you land?

**Comment by sam-github** [comment]
Landed in 28ae71a

**Pull request closed without merging**
