### PR TITLE
Limit titles to 150 characters, with no linebreaks

### PR DESCRIPTION
**Pull request by greysteil**
As suggested in #200.

### CODE REVIEW

**Comment by greysteil** [comment]
Just because it was the first number that came into my head, but you're right - it's a bit long.

The longest title we have currently is 68 characters. Could set this to 70?

**Comment by lirantal** [comment]
I don't think we should decide just like that on the number since it can break the workflow in some circumstances.

The title is taken from the HackerOne report field for weakness and the longest I've seen is give or take 100 chars. If there will be a longer weakness title though will it break the workflow? will it truncate? etc

So I'd suggest we:
1. Try to identify with HackerOne what's the longest a weakness title can have
2. If (1) doesn't pan out easily then we can put a reasonable high limit like 200 chars

**Comment by greysteil** [comment]
👍 - I've pinged the HackerOne folks and asked them to comment here.

**Comment by Tulipants** [comment]
image
 Hey All,   The max characters for reports on HackerOne is 150.  :)

**Comment by greysteil** [comment]
Awesome, thanks @Tulipants.

@lirantal - I've updated this accordingly.

**Comment by lirantal** [comment]
Great, thanks @Tulipants @greysteil!

**Pull request merged**
