### PR TITLE
Prefer null to blank strings

### PR DESCRIPTION
**Pull request by greysteil**
Be a little more of a hard-arse on validations, and update all existing advisories so they use `null` instead of blank strings.

### CODE REVIEW

**Comment by greysteil** [comment]
I want to consume the data in a Ruby application, where blank strings are truthy and `nil` values are falsey. I can easily handle that on my side, but it strikes me that lots of consumers may have to write the same logic. Maybe better to have it enforced strictly here?

Given that it's easy to validate, and to have Travis run those validations, my thinking was that keeping the data really clean here will stop people consuming the info getting a nasty surprise later.

**Comment by vdeturckheim** [comment]
To be clear, right now, there is no plan to have travis running on this (see https://github.com/nodejs/security-wg/pull/102). Travis file is an artifact and I should not have merged it.

**Comment by greysteil** [comment]
That's too bad - why not? The linting looks pretty good to me.

**Comment by vdeturckheim** [comment]
@greysteil as of https://github.com/nodejs/security-wg/pull/102#issuecomment-367348949, it seems easier for us to integrate this into existing Node.js Jenkins.

**Comment by greysteil** [comment]
Cool, well that makes sense to me if it's imminent!

**Comment by greysteil** [comment]
@vdeturckheim does this look good to merge to you?

**Pull request merged**
