### PR TITLE
workflow: add update core/npm indexes

### PR DESCRIPTION
**Pull request by RafaelGSS**
Following up #864

### CODE REVIEW

**Comment by RafaelGSS** [comment]
It's still a draft because I need to test it locally.

**Comment by mhdawson** [comment]
Thanks for putting this together. Looks good so far.

**Comment by RafaelGSS** [comment]
@mhdawson can I get your approval?

**Comment by fraxken** [comment]
@RafaelGSS Where are those two `update-` npm scripts? In package.json there is only `create-` scripts.

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by RafaelGSS** [comment]
> @RafaelGSS Where are those two `update-` npm scripts? In package.json there is only `create-` scripts.

Fixed. Forgot about it.

**Review by UlisesGascon — APPROVED** [review]

**Pull request merged**
