### PR TITLE
Offboard Daniel Ruf

### PR DESCRIPTION
**Pull request by DanielRuf**
Please also revoke relevant access.

### CODE REVIEW

**Review by RafaelGSS — APPROVED** [review]
Thank you for all of your hard work!

**Review by UlisesGascon — APPROVED** [review]
Thanks for all the contributions, @DanielRuf!

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by mhdawson** [comment]
Removed from nodejs/security-wg team

**Pull request merged**
