### PR TITLE
Strawman to start discussion about possible goals

### PR DESCRIPTION
**Pull request by mikesamuel**
This patch probably does not currently represents the consensus of members.
I offer it to start a discussion about whether either of these bullet points describe things the security working group should do.

> Maintain linter policies that encode community knowledge about common security
  anti-patterns.

[JSConformance](https://github.com/google/closure-compiler/wiki/JS-Conformance-Framework) allows a project team to specify a policy for closure JavaScript that they use.  This policy can encode lessons learned about APIs that are prone to misuse and can take into account type information about arguments and `this`-values.

[tslint][] and [eslint][] both allow custom rules.

[tslint]: https://palantir.github.io/tslint/develop/custom-rules/
[eslint]: https://eslint.org/docs/developer-guide/working-with-rules-new#runtime-rules

Some APIs and idioms are more prone to misuse than others, and some should be deprecated in favor of more robust ways of expressing the same idea.
As the community reaches a rough consensus that a code pattern is prone to misuse  or there is a more robust alternative, we could try to encode that knowledge in an automatable policy.

The goal is not to tell package developers what to do, but to
-  make information about alternatives available at the point where it is most relevant to them.
-  allow package consumers to make more informed decisions about the hazards that
   might occur from passing an untrusted input to an API 
 

Tslint typically has more fine-grained type information available than eslint, so there are probably more anti-patterns that can be identified with an acceptable false-positive rate in tslint than eslint, but feedback about what can and can't be expressed in eslint might give eslint maintainers useful feedback. 

----

> Make it easier to identify NPM packages with mature, security-cognizant
> development practices so that application developers can build on a robust
> foundation and make informed decisions about when to use bleeding-edge code.

A wise technical lead might decide that they can allow their developers to use third-party dependencies that have been widely used in production for several years by projects with a similar structure since gross errors are likely to have been found and identified.
That technical lead might also decide that they can use bleeding edge code when they have enough local expertise to vet it, identify corner-cases they need to check, and fix any gross errors they encounter.

We can support wise tech leads without giving the appearance of picking favorite packages by aggregating signals about project maturity :

The [Best practices](https://github.com/coreinfrastructure/best-practices-badge) project has some ideas about signals that might be of interest.

Other sources of information we might look at include:

- Linter results ignoring local overrides for a package and its transitive dependencies
- Github pulse information for a packages and its transitive dependencies including sustained contributor count
- Version staleness among transitive dependencies

Thanks for reading this far.

### CODE REVIEW

**Comment by cjihrig** [comment]
I think these are great ideas, but I'm not sure if this working group is the right place for some of those things.

For example, publishing linting rules can seen as Node picking a winner. Granted, Node core uses ESLint, but we don't really advocate for using our config outside of core.

> Github pulse information for a packages and its transitive dependencies including sustained contributor count

Those can be misleading numbers sometimes. Sometimes a module is just "done."

I'd say I'm -0 on this, but wouldn't try to block any work if others think it's useful.

**Comment by mikesamuel** [comment]
@cjihrig

I can provide examples of linter rules if that might help move you from a -0 to +0.

A module can be done.  But in my experience, there's still churn on issue lists, doc updates, and the occasional push to update dep versions as bugs are fixed there.

Do you know of a better forum if this is out of scope for security-wg?

**Comment by cjihrig** [comment]
> Do you know of a better forum if this is out of scope for security-wg?

My inclination is that a lot of those things could be (and I believe currently are) done by companies. I'm happy to have others weigh in though.

**Comment by mhdawson** [comment]
My first thought is we have a long way to go in terms of just getting ramped up to accept reports and manage the security data for modules before we'd have the cycles in this team to consider tooling/etc. to generate/consume additional data that might factor into module selection.

In terms of a better forum, it sounds as if you might want to get together people who are interested in working on 'module validation/certification'.  I think a good first step is to see how many people in this WG chime in as being interested in that or know somebody else in their company who might be.

**Comment by vdeturckheim** [comment]
I have the feeling that this would be interesting, but at the moment we have no real idea about how to do that.

We are barely starting to collect vulnerabilities for the ecosystem. Once we are used to doing that and have sufficient experience regarding what the ecosystem securities issues are, we can start to issue advice and best practices.

However, I would not go on the way to push on specific tool forward as it might feel like "the official tool for XXX is YYY".

**Comment by mikesamuel** [comment]
Thanks for all the replies.

The prevailing theme seems to be maybe some on the committee would be interested in contributing here or elsewhere, but there's more pressing matters to deal with first.

**Pull request closed without merging**
