### PR TITLE
Onboard Eva Sarafianou to the WG

### LINKED ISSUE #657: Nominate Eva Sarafianou to the triage team
Hi @nodejs/security-wg

I would like to nominate Eva Sarafianou (@esarafianou) to the triage team.

Eva is a product security engineer at Auth0. She brings tons of experience with vulnerability management and JavaScript security and I am confident she will be a great asset to the team.

I can onboard Eva to our processes.

### PR DESCRIPTION
**Pull request by esarafianou**
Adding myself to the members; fixes #657

### CODE REVIEW

**Comment by MarcinHoppe** [comment]
Don't forget to add yourself here, too: https://github.com/nodejs/security-wg/blob/master/processes/third_party_vuln_process.md#members.

**Comment by esarafianou** [comment]
Updated

**Comment by esarafianou** [comment]
Rebased on updated master

**Comment by MarcinHoppe** [comment]
@sam-github @mhdawson can you add @esarafianou to the @nodejs/security-wg team?

**Pull request merged**
