### PR TITLE
Nominate Andreas Tiefenthaler to the WG

### PR DESCRIPTION
**Pull request by vdeturckheim**
I'd like to nominate Andreas Tiefenthaler (@pxlpnk) to the Working Group. Andreas has been actively helping us with the vulnerability database and I believe he would be a great asset to this team.

### CODE REVIEW

**Comment by lirantal** [comment]
+1 a great addition indeed

**Comment by vdeturckheim** [comment]
@nodejs/security-wg I will be merging this on Sunday or Monday. Please check this before ;)

**Comment by vdeturckheim** [comment]
Merging :D congrats @pxlpnk
@cjihrig or @mhdawson can you invite @pxlpnk to the org and WG please?

**Comment by cjihrig** [comment]
Invites sent.

**Comment by vdeturckheim** [comment]
Thanks @cjihrig !

**Comment by pxlpnk** [comment]
Thank you @cjihrig

**Pull request merged**
