### PR TITLE
Responsible Disclosure Policy template for 3rd party module authors

### PR DESCRIPTION
**Pull request by lirantal**
Addressing #93 with regards to a template that 3rd party module authors can use in their projects as a `SECURITY.md` resource.

Some general notes:
- I liked @vdeturckheim's "Report a Vulnerability" button thing. I was immediately thinking about a README badge kind of thing. Would be cool to experiment with some "security badge" concepts.
- Bugcrowd created a [richer version](https://github.com/bugcrowd/disclosure-policy/blob/master/responsible_disclosure_policy.md) of this that was meant to be adopted by projects, though I find it a full blown policy while we already have the policy defined and would want to optimize for engagement with short and clear security awareness.

Looking forward for review on style, structure and contents of the template.

### CODE REVIEW

**Comment by vdeturckheim** [comment]
I like it, I think it misses instructions on how to use. Wdyt?

**Comment by vdeturckheim** [comment]
@lirantal I played a bit with svg (based on https://github.com/dwyl/repo-badges ). Here is a potential badge
```
<svg xmlns="http://www.w3.org/2000/svg" width="150" height="20">
    <rect rx="3" width="150" height="20" fill="#555"/>
    <g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="13">
        <text x="50%" y="70%">report vulnerability</text>
    </g>
</svg>
```
<svg xmlns="http://www.w3.org/2000/svg" width="150" height="20">
    <rect rx="3" width="150" height="20" fill="#555"/>
    <g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="13">
        <text x="50%" y="70%">report vulnerability</text>
    </g>
</svg>

**Comment by lirantal** [comment]
@vdeturckheim do you mean 'how to use' from the maintainer perspective? If so, I thought we would just use this as a template where they can simply copy (in the future, maybe we can come up with some nice github security bots to open a PR etc)

**Comment by vdeturckheim** [comment]
@lirantal yes, I was thinking of guidelines on how to handle security for your repo including having a SECURITY.md or a security part of README. but might be more of a future work.

**Pull request merged**
