### PR TITLE
Add Liran Tal to vulnerability triage team

### PR DESCRIPTION
**Pull request by lirantal**
Requesting to be part of the triage team

### CODE REVIEW

**Comment by cjihrig** [comment]
I'm not trying to be difficult, but based on the discussion in https://github.com/nodejs/security-wg/pull/76, I think each person has to send their own PR.

**Comment by lirantal** [comment]
@cjihrig not an issue at all, updated :)

**Comment by lirantal** [comment]
Cool, updated.

**Comment by vdeturckheim** [comment]
@lirantal I would love to have you in the team. Because of process, we need to merge https://github.com/nodejs/security-wg/pull/80 first (therefore, have a few 👍  there).

**Comment by lirantal** [comment]
Gotcha! I've been following quietly the past couple of months on the repo but missed that, thanks! ;-)

**Comment by lirantal** [comment]
@vdeturckheim I squashed and updated the triage team list

**Comment by vdeturckheim** [comment]
I just invited you to the private github team and the HackerOne team. Welcome ;)

**Comment by lirantal** [comment]
Yep, I'm there!
You're welcome to assign any incoming new issues for me to handle.

**Pull request merged**
