### PR TITLE
chore: write index files with indented format

### PR DESCRIPTION
**Pull request by nschonni**
Opening as a draft as you'll notice the NPM index is now empty. Doesn't seem related to this change, and I can rebase it out if you'd like to land the NPM part for now

### CODE REVIEW

**Comment by UlisesGascon** [comment]
Great work @nschonni! I will create a separate PR to patch the npm index generation bug

**Comment by UlisesGascon** [comment]
@nschonni this should fix the problem with the Npm Index generation https://github.com/nodejs/security-wg/pull/920

**Review by UlisesGascon — APPROVED** [review]

**Comment by nschonni** [comment]
OK, I've just rebased out the NPM file for now if you want to land this while you work on fixing the other generation

**Comment by nschonni** [comment]
PS: I noticed the CI isn't running `npm test` which is also currently failing locally for me

**Comment by UlisesGascon** [comment]
Created issue https://github.com/nodejs/security-wg/issues/922

**Pull request merged**
