### PR TITLE
doc: courtesy heads-up

### PR DESCRIPTION
**Pull request by refack**

### CODE REVIEW

**Comment by refack** [comment]
> I'm not a big fan of formally documenting this because it may not be necessary or practical.

Added after my personal experience yesterday https://github.com/nodejs/nodejs.org/pull/1379#issuecomment-332654876. It's not the nicest feeling being the last one to know you messed up.
IMHO if we ***can*** be courteous I believe we should, but I get what you're saying about it not being very practical.

**Comment by cjihrig** [comment]
> It's not the nicest feeling being the last one to know you messed up.

No one likes the feeling of introducing bugs, but I don't really see the point here. The bug fix needs to be released no matter what. When the original author of the bug finds out about it seems inconsequential. The only exception I see would be if the original author has some domain expertise, and can get the bug fixed significantly faster/easier.

**Comment by sam-github** [comment]
I'm -1 on this @refack. Unfortunately, because we aren't using a tool like HackerOne, the conversation about this will be perpetually embargoed so you can't see it, but at no point was it discussed who authored the code that introduced the bug, much less who reviewed it. I can't imagine anybody caring. Digging through the history to find everyone who commented on a PR and telling them the PR introduced a bug in a corner case that was not covered by the test suite is a lot of work, and the sec process is arduous enough already.

**Comment by refack** [comment]
> the conversation about this will be perpetually embargoed

That's well understood.
I tried to add the *Note* in the softest terms, and at a stage after the embargo is lifted.
As for caring, I can attest that the people involved might care out of personal responsibility.

Bottom line: even if this isn't formally documented, IMHO it's good to keep in mind that there are people behind the avatars and GPG signatures, and courtesy is usually not expensive to give but very valuable to receive.

**Comment by mhdawson** [comment]
I'd suggested to @refack to submit this.  If we don't have something to remind people to think about this aspect it can be easily overlooked.    We might change it to something like "if the release blog obviously points to somebody as having caused the issue (for example reverting a commit), adding that person as a cc on the PR for the blog post to give them a heads up might be appropriate.

**Comment by sam-github** [comment]
OK, that more specific language sounds better. Note that would have been targos, in this specific case, not refack, AFAICT @refack only reviewed.

**Comment by mhdawson** [comment]
@cjihrig you ok with language along the lines that I suggested ?

**Comment by mhdawson** [comment]
@refack would like like to update the PR along the suggested lines ?

**Comment by refack** [comment]
Changes working based on @mhdawson's suggestion but pluralized it

**Comment by mhdawson** [comment]
Landed as 886d2dbf9725737424ccee8de8ae42cb102d4870

**Pull request closed without merging**
