### PR TITLE
doc: mark Permission Model as completed

### PR DESCRIPTION
**Pull request by RafaelGSS**
Refs: #898

### CODE REVIEW

**Comment by mcollina** [comment]
I think we should mark it as completed when/if we graduate it to stable?

**Comment by RafaelGSS** [comment]
> I think we should mark it as completed when/if we graduate it to stable?

That's the initiative, the first iteration. We'll keep working on that but with different tasks (which will be renamed to Permission Model - 3 Phrase)

**Review by mhdawson — APPROVED** [review]
LGTM

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
