### PR TITLE
dgonzalez into the security working group

### PR DESCRIPTION
**Pull request by dgonzalez**
As requested in https://github.com/nodejs/security-wg/pull/155. If we need any supporting evidence of my work around security I can provide.

### CODE REVIEW

**Comment by vdeturckheim** [comment]
@nodejs/security-wg heads up :)

**Comment by vdeturckheim** [comment]
lgtm. Merging. Congrats @dgonzalez :)

**Comment by vdeturckheim** [comment]
@dgonzalez you might want to join our slack :)

**Comment by dgonzalez** [comment]
Thanks! I am already on Slack.

**Comment by vdeturckheim** [comment]
@jasnell if you are still around, can you add @dgonzalez to the Org please?

**Comment by gibfahn** [comment]
@dgonzalez invitation to join nodejs/security-wg sent.

**Pull request merged**
