### PR TITLE
Add Alex Knol to Security WG / Triage team

### PR DESCRIPTION
**Pull request by Elexy**

### CODE REVIEW

**Comment by lirantal** [comment]
Welcome Alex!

FYI the names are ordered alphabetically based on the username so you'd need to edit it.
Also, you should probably review:
 - https://github.com/nodejs/security-wg/blob/master/processes/security_team_onboarding.md first for a list of "how to start". I assume @dgonzalez will be your designated buddy to show you around the repo, the hackerone platform, etc.
 - and then review the rest of the processes docs etc

I'll be happy to help with anything if you have any questions.
Excited to have you joining us ;-)

**Comment by dgonzalez** [comment]
LGTM!

**Comment by dgonzalez** [comment]
If no one has any objections I will merge it on Tuesday.

**Comment by vdeturckheim** [comment]
I'll merge this. @dgonzalez do you want to handle @Elexy 's 3rd party triage team onboarding? I can do it otherwise.

**Pull request merged**
