### PR TITLE
chore(member): add myself as new member

### PR DESCRIPTION
**Pull request by DanielRuf**
I hereby accept the nomination in #614 and propose the following
addition to the Security WG members list and especially to the Ecosystem
Triage team.

I have read and understood all processes files and the rules outlined in
the Code of Conduct document.

@lirantal is my buddy who leads me through the on-boarding process.

### CODE REVIEW

**Comment by lirantal** [comment]
@DanielRuf I'll land this so we can get you going.
Can you join our Node.js Security WG slack and follow the rest of the onboarding asks? I'll then schedule some time for us to review triage of vulns on H1

**Comment by DanielRuf** [comment]
> Can you join our Node.js Security WG slack and follow the rest of the onboarding asks? I'll then schedule some time for us to review triage of vulns on H1

Done. But I think I can not yet see the mentioned private discussion =)

**Comment by lirantal** [comment]
@mhdawson can we invite @DanielRuf to the Node.js org?

**Comment by sam-github** [comment]
@lirantal  SGTM. Do you need to do that to add him to https://github.com/orgs/nodejs/teams/ecosystem-security? I can do it if you don't have enough privs.

**Comment by lirantal** [comment]
@sam-github  Yes I don't have access to that, if you can please add him to the Node.js org and to the team that would be super. I'll then be able to also send him H1 invites and we'll go over the triage thing in an onboarding call.

Thanks Sam!

**Comment by sam-github** [comment]
Invite sent.

**Pull request merged**
