### PR TITLE
Replace final few empty strings with null

### PR DESCRIPTION
**Pull request by greysteil**
A few of these crept in before https://github.com/nodejs/security-wg/pull/218 was merged, and the validation in https://github.com/nodejs/security-wg/pull/219 wasn't updated for that PR. This fixes both issues.

### CODE REVIEW

**Comment by lirantal** [comment]
so we're only going to allow nulls, right?

did we collect some feedback from @ChALkeR or @dgonzalez who have been building tooling around the vuln db as well to see we're not breaking anything in particular?

**Comment by greysteil** [comment]
Doesn't look like they chimed in on #218, so no, but feedback welcome. Hopefully being stricter here makes things simpler for everyone.

**Comment by greysteil** [comment]
Worth mentioning that in the meantime, without this PR, linting on master is broken - might be worth merging this and then reverting both is and #218 if there's a change of mind?

**Comment by greysteil** [comment]
@ChALkeR / @dgonzalez - any opinions on this? Don't want it to go stale.

**Comment by vdeturckheim** [comment]
Let's merge :) thanks a lot @greysteil

**Comment by lirantal** [comment]
Please do! 🎉

**Pull request merged**
