### PR TITLE
feat(3rd-triage-team): Add @dgonzalez to the triage team

### PR DESCRIPTION
**Pull request by dgonzalez**

### CODE REVIEW

**Comment by vdeturckheim** [comment]
Hey @dgonzalez . Thanks for this PR. As indicated in https://github.com/nodejs/security-wg/blob/master/processes/third_party_vuln_process.md#the-triage-team , you need to be a member of the WG before joining this team. Can you please PR yourself as a member of the WG?

**Comment by dgonzalez** [comment]
Yes, I was not aware of it... let me PR.

**Comment by dgonzalez** [comment]
@vdeturckheim done: https://github.com/nodejs/security-wg/pull/158

**Comment by vdeturckheim** [comment]
Heads up @nodejs/security-wg

**Comment by vdeturckheim** [comment]
I'll merge this tomorrow if nobody objects :)

**Comment by vdeturckheim** [comment]
Congrats @dgonzalez ! I'll ping you on Slack for the next steps

**Pull request merged**
