### PR TITLE
ci: workflows permissions hardening

### PR DESCRIPTION
**Pull request by fraxken**
Hello 👋

I'm starting to look at improving the security issues in relation to the scorecard. One of the issue is the lack of top level permissions in our workflows.

> **Note** Github documentation about jobs permissions: [Assigning permissions to jobs](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs)

I updated permissions for all workflows, however I had doubt for `update-core-index` and `update-npm-index`.

- Stale: I followed the [recommendations](https://github.com/actions/stale#recommended-permissions) for `actions/stale@v5`.
- Validate vulnerability: `contents` read is from what I see from my own projects enough to run Node/npm scripts.

This is a first step.

### CODE REVIEW

**Review by RafaelGSS — COMMENTED** [review]
I'm thinking that perhaps it's better to remove the `update-core/npm-index.yml` and do it manually through a PR. That seems safer.

**Comment by fraxken** [comment]
@RafaelGSS done

**Review by RafaelGSS — APPROVED** [review]

**Comment by RafaelGSS** [comment]
@fraxken Can you remove the update-core/npm-index.yml?

**Review by UlisesGascon — APPROVED** [review]

**Comment by fraxken** [comment]
@RafaelGSS I already removed it last time, should be good now

**Pull request merged**
