### PR TITLE
Use yyyy-mm-dd format for publish_date

### PR DESCRIPTION
**Pull request by greysteil**
Implements https://github.com/nodejs/security-wg/issues/171.

I've kept the `created_at` and `updated_at` attributes as timestamps, because I think that makes sense, but changed the `publish_date` format to be an ISON 8601 date.

I've also added newlines to the JSON, because I think that's standard for most folks - happy to change that, though.

### CODE REVIEW

**Comment by greysteil** [comment]
@dgonzalez - are you the right person to review, given that you created #171 ?

**Comment by dgonzalez** [comment]
Let me do it.

**Comment by dgonzalez** [comment]
LGTM

**Comment by vdeturckheim** [comment]
Thanks for this :D

**Comment by lirantal** [comment]
great stuff @greysteil and I like the ISO 8601 usage in our rules and vulnerabilities.

**Pull request merged**
