### PR TITLE
Nominating André Eleuterio to join the Security WG

### PR DESCRIPTION
**Pull request by ronperris**
I have spoken to André Eleuterio ([twitter](https://twitter.com/eleuterio_), [linkedin](https://www.linkedin.com/in/andr%2525C3%2525A9-eleuterio-a4570a128), [npm](https://www.npmjs.com/~andreeleuterio)) and he would like to join the Security WG.

André triages vulnerabilities for NPM in both the npm tooling and ecosystem packages.

He is keen to join the Security WG and the vulnerability triage team.

Having a member of the NPM team, like André, will help coordinate efforts and communications.

### CODE REVIEW

**Comment by sam-github** [comment]
@ronperris could you include links to his public profiles (github, linked in, npm) so his identity is more clear?

**Comment by sam-github** [comment]
Also, some evidence that he wants to join! I'm sure he did in private with you, but I wouldn't want to land this without a "Hello, I'm Andre, and I want to join" message.

**Comment by aeleuterio** [comment]
Hey everyone! I'm Andre from the npm security team. I work with triaging vulnerability reports for npm and would love to help the Node security-wg efforts with triaging efforts. This was discussed with the npm security team and we're excited to partake in this effort that is so beneficial for npm users. Looking forward to it!

**Comment by sam-github** [comment]
Its great to have involvement from npm, thanks.

**Comment by lirantal** [comment]
Great to have your involvement with the group @aeleuterio

**Comment by MarcinHoppe** [comment]
Welcome @aeleuterio !

**Comment by sam-github** [comment]
@aeleuterio were you onboarded? You don't look to me to have H1 access, despite being listed on the Triage team.

**Pull request merged**
