### PR TITLE
doc: add RafaelGSS as a Security WG member

### PR DESCRIPTION
**Pull request by RafaelGSS**

### CODE REVIEW

**Comment by mhdawson** [comment]
@nodejs/security-wg

**Review by vdeturckheim — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Review by MarcinHoppe — APPROVED** [review]

**Review by UlisesGascon — APPROVED** [review]
LGTM! 🚀

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mhdawson** [comment]
This looks to me to have been approved by the most active members and I don't see any objections.

**Pull request merged**
