### PR TITLE
vuln: update core and npm index.json

### PR DESCRIPTION
**Pull request by RafaelGSS**
Looks like we missed this workflow in the past security releases.

This PR introduces the list generated by `npm run create-core-index` and `npm run create-npm-index`.

I will open another pull request to generate this automatically whenever a new entry was added in the vuln/ folder.

### CODE REVIEW

**Comment by RafaelGSS** [comment]
By the way, I'm working on https://github.com/nodejs/security-wg/issues/852 and I need this index.json file.

**Review by vdeturckheim — APPROVED** [review]

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by mhdawson** [comment]
@RafaelGSS could we have an action that automatically creates a PR on an update to the vulns?

**Comment by RafaelGSS** [comment]
> @RafaelGSS could we have an action that automatically creates a PR on an update to the vulns?

Yes, refactoring #865

**Pull request merged**
