### PR TITLE
Cleanup CI and deps

### PR DESCRIPTION
**Pull request by vdeturckheim**
remove yarn.lock
add package-lock.json (see https://github.com/nodejs/security-wg/pull/217)
remove .travis.yml (see https://github.com/nodejs/security-wg/pull/102#issuecomment-367348949)

### CODE REVIEW

**Comment by mhdawson** [comment]
I'm wondering if it makes sense to have the package-lock.json at the top level of the repo.  Does it need to be at the top level or could it be in a subdirectory like `tooling`

**Comment by vdeturckheim** [comment]
@mhdawson I don't know npm enough :thinking: I'll test it!

**Comment by lirantal** [comment]
Even if we'll have tooling inside `tooling/` or `src/` directories, it might make sense to keep a top-level `package.json` for the sake of easily running scripts instead of always changing dirs.

**Comment by greysteil** [comment]
👍 from me. I'd really like to have the linting running on some form of CI, though - how far away is getting Jenkins set up, and does it make sense to use Travis in the short term?

**Comment by lirantal** [comment]
joining @greysteil about having a CI. Where does that stand @vdeturckheim / @mhdawson ?
besides that I think we can merge this one to give us the package-lock.json file

**Comment by vdeturckheim** [comment]
@lirantal I need to dig into JenkinsFiles for this.

**Pull request merged**
