### PR TITLE
chore(member): add Thomas Gentilhomme as new member

### PR DESCRIPTION
**Pull request by fraxken**
Adding myself to the README.md.

Issue related to my in progress nomination:
https://github.com/nodejs/security-wg/issues/678

### CODE REVIEW

**Review by vdeturckheim — APPROVED** [review]

**Review by MarcinHoppe — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by MarcinHoppe** [comment]
@fraxken do you want to join the WG, or also the H1 triage team? It is fine to join the WG but not the H1 triage team but I just wanted to call it out explicitly.

**Comment by fraxken** [comment]
@MarcinHoppe I am not familiar with the triage process so i guess no ^^.

**Comment by MarcinHoppe** [comment]
@fraxken That is totally fine, I just wanted to bring this to your attention: https://github.com/nodejs/security-wg/blob/master/processes/third_party_vuln_process.md.

**Comment by vdeturckheim** [comment]
@nodejs/security-wg let's mergi this on Monday if nobody opposes?

**Comment by MarcinHoppe** [comment]
👍 here!

**Pull request merged**
