### PR TITLE
Update README.md

### LINKED ISSUE #365: doc: WG is chartered
[WORKING_GROUPS.md#security](https://github.com/nodejs/TSC/blob/master/WORKING_GROUPS.md#security) is there, https://github.com/nodejs/TSC/pull/548 landed, https://github.com/nodejs/TSC/issues/486 is resolved, but [Readme states](https://github.com/nodejs/security-wg#security-working-group): 

> ## Security Working Group
> Note: this group is in the process of seeking Charter by the TSC (https://github.com/nodejs/TSC/issues/486)

That should be updated, as I presume. /cc @mhdawson @vdeturckheim

### PR DESCRIPTION
**Pull request by Trott**
Fixes #365

### CODE REVIEW

**Comment by ChALkeR** [comment]
Can this mention https://github.com/nodejs/security-wg/issues/365 in the commit?

**Comment by Trott** [comment]
@ChALkeR Sure, done!

**Comment by ChALkeR** [comment]
@Trott I believe this is superseded by https://github.com/nodejs/security-wg/pull/369 :wink:.

**Comment by Trott** [comment]
I don't know the process in this repository. Can this land at this time? (Or if #369 is ready to land, then land that one and close this one?)

**Comment by Trott** [comment]
#369 landed, which supersedes this.

**Pull request closed without merging**
