### PR TITLE
vuln(NSWG-ECO-440): serve module update

### PR DESCRIPTION
**Pull request by lirantal**

### CODE REVIEW

**Comment by evilpacket** [comment]
Is this a different bug than https://github.com/nodejs/security-wg/blob/master/vuln/npm/439.json ?

**Comment by MarcinHoppe** [comment]
Good catch @evilpacket. The CVE and H1 report are the same in both entries.

**Comment by lirantal** [comment]
Ugh, right. So looks like we have a duplicate then.
How about I go ahead and delete the 440 report to release that entry ?

**Comment by MarcinHoppe** [comment]
👍

**Comment by lirantal** [comment]
@evilpacket ? just to check if we missed anything

**Comment by evilpacket** [comment]
@lirantal I don't think so, looks like a dupe to me.

**Pull request merged**
