### PR TITLE
Adding myself to the Members List based on #434 

### PR DESCRIPTION
**Pull request by matt-**
I wanted to add myself to the members section based on: 

https://github.com/nodejs/security-wg/issues/434

### CODE REVIEW

**Comment by lirantal** [comment]
welcome back 🙌

**Comment by lirantal** [comment]
@matt- still relevant?

**Comment by vdeturckheim** [comment]
@matt- is this still up to date?

**Comment by esarafianou** [comment]
We're closing this issue due to lack of activity.

**Pull request closed without merging**
