### PR TITLE
Nominate Brandon Kobel as member of the WG

### PR DESCRIPTION
**Pull request by kobelb**
I'd like to nominate myself as a member of the security working-group.

I currently work on a security focused team with @watson for a product built using Node.js. I'd like to contribute to improving the security of core Node.js, and encourage the adoption of secure coding practices within the community itself.

### CODE REVIEW

**Comment by sam-github** [comment]
+1

**Comment by kobelb** [comment]
> LGTM, but can you keep this list sorted by GitHub handle.

Yup, you got it!

**Comment by fraxken** [comment]
Hello 👋 

What is the status of this PR? @kobelb Do you still want to be a member of this working group?

**Comment by kobelb** [comment]
@fraxken no thanks, thanks for checking in.

**Pull request closed without merging**
